### ISSUE TITLE
i can't read with the player the disk i have do with the recorder :'( 

### ISSUE THREAD

**Issue by AlChimiK2D** [NicholasFeldman/BetterRecords#36]
BetterRecords: `BetterRecords-1.12.2-1.5.5`  
Forge: `forge-1.12.2-14.23.2.2611-universal`

# Issue
![bugbr](https://user-images.githubusercontent.com/30317409/38674218-f8c88ce0-3e53-11e8-80c4-26f550765108.png)

# Steps to Reproduce
1. i do a disk with the mod, it's ok to etch
2. i etch and i have a disk but when i give it to the player, there's the problem.

Link to crash log: <no crash log>

**Comment by LordXerus** [comment]
1. There is no crash
2. What happens if you put the link you used to etch the record into your browser?
3. What is the link?
4. If you put the link into Firefox or Chrome, it looks kinda like this (A little player bar, without anything else)
![default](https://user-images.githubusercontent.com/34696211/44142829-1301cdb6-a0b4-11e8-9018-b9aa3227ef0f.PNG)

**Comment by NicholasFeldman** [comment]
Please try with `1.12.2-1.5.6`, and re-open if your issue persists, providing more information, specifically the URL used.
