### ISSUE TITLE
No 1.7.10 version?

### ISSUE THREAD

**Issue by BinaryDust** [NicholasFeldman/BetterRecords#85]
Hello

I don't really know where to ask my question, so i've put it there, sorry if it's not the right place.
I'm currently trying to create a modpack for a private server and the other players asked me if it was possible to install BetterRecord, but as i've seen, there is no more link for the 1.7.10 version.

I've search it on nearly every places but i've found nothing about the version of your mod i wanted or some information about the lack of this version. I've even tryed to launch the 1.7.2 version but it doesn't work.

I don't know if you'll allow us to reuse this version or at least if we can still have some informations about the lack of this version .

Best regards,
BinaryDust

**Comment by NicholasFeldman** [comment]
A lot of the 1.7.10 version was written before I took over the project, and did some major refactoring. The 1.7.10 version relied on some external web resources that may or may not be available, as well as contained many game breaking/crashing bugs. Because of this, 1.7.10 versions were taken down. There are no plans to support a five year outdated version.

I'll update the FAQ's with this information.
